version: '3.0'

services:
  apache:
    build: ./apache
    ports: 
      - "127.0.0.1:80:80"
  exo:
    image: exoplatform/exo:5.2_latest
    environment:
      EXO_DB_NAME: exo
      EXO_DB_USER: exo
      EXO_DB_PASSWORD: exo
      EXO_DB_HOST: db
      EXO_PROXY_VHOST: exo.docker.local
      EXO_PROXY_SSL: "false"
      EXO_JVM_SIZE_MIN: "2g"
      EXO_JVM_SIZE_MAX: "3g"
      EXO_JVM_LOG_GC_ENABLED: "true"
      EXO_MAIL_SMTP_HOST: "mail"
      EXO_MAIL_SMTP_PORT: "1025"
      EXO_ES_EMBEDDED: "true"
    volumes:
      - exo_data:/srv/exo
      - exo_logs:/var/log/exo
    links:
      - db
      - mongo
    depends_on:
      - db
      - mongo
      - mail

  mongo:
    image: mongo:3.6
    volumes:
      - mongo_data:/data/db:rw

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: exo
      MYSQL_USER: exo
      MYSQL_PASSWORD: exo
    volumes:
      - db_data:/var/lib/mysql:rw

  mail:
    image: mailhog/mailhog
    environment:
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_STORAGE: mongodb
      MH_MONGO_URI: mongo:27017
      MH_MONGO_DB: mailhog
      MH_MONGO_COLLECTION: messages
      MH_UI_WEB_PATH: mail

volumes:
  exo_data:
  exo_logs:
  db_data:
  mongo_data:
